### ISSUE TITLE
Component config object can't be extended with `head` property

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/nuxt-class-component#18]
### Version

[v1.2.1](https://github.com/nuxt-community/nuxt-class-component/releases/tag/v1.2.1)

### Reproduction link

[https://github.com/nuxt-community/nuxt-class-component](https://github.com/nuxt-community/nuxt-class-component)

### Steps to reproduce

- Create a component using @Component decorator
- Pass `head` property to a config object

### What is expected ?

Title of the related page is changed

### What is actually happening?

```
[tsl] ERROR in ...\nuxt-apollo-github\components\Inspirations.vue.ts(20,3)
      TS2345: Argument of type '{ head: { title: string; }; }' is not assignable to parameter of type 'VueClass<Vu
e>'.
  Object literal may only specify known properties, and 'head' does not exist in type 'VueClass<Vue>'.
```

### Additional comments?

Same is happening with other custom properties. For example, if you try to use @nuxt/apollo module and it's apollo config property you will also get an error:
```
TS2345: Argument of type '{ apollo: { allInspirations: { prefetch: boolean; query: DocumentNode; }; }; head:
 { title: strin...' is not assignable to parameter of type 'VueClass<Vue>'.
  Object literal may only specify known properties, and 'apollo' does not exist in type 'VueClass<Vue>'.
```
I think any other custom property will also produce similar error.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-class-component/issues/c9">#c9</a>)</em></sub></div>

**Comment by husayt** [comment]
I recommend using "nuxt-property-decorator", which covers all the features of this module and you can see "head" working [here](https://codesandbox.io/s/1q478mzyvj)

**Comment by hdsuperman** [comment]
@AndrewBogdanovTSS
```typescript
Component.registerHooks([
  'beforeRouteEnter',
  'beforeRouteLeave',
  'beforeRouteUpdate', // for vue-router 2.2+
  'head',
]);
```
